import { Verb } from './types';

export const INITIAL_VERBS: Verb[] = [
  {
    id: 'v1',
    base: 'go',
    past: 'went',
    participle: 'gone',
    meaning: '가다',
    example: 'I usually go to work by bus, but yesterday I went by taxi.',
    isIrregular: true,
  },
  {
    id: 'v2',
    base: 'eat',
    past: 'ate',
    participle: 'eaten',
    meaning: '먹다',
    example: 'Have you eaten lunch yet? I ate an hour ago.',
    isIrregular: true,
  },
  {
    id: 'v3',
    base: 'write',
    past: 'wrote',
    participle: 'written',
    meaning: '쓰다',
    example: 'She wrote a letter to him, but she hasn\'t written the address yet.',
    isIrregular: true,
  },
  {
    id: 'v4',
    base: 'play',
    past: 'played',
    participle: 'played',
    meaning: '놀다/연주하다',
    example: 'We played soccer last Sunday.',
    isIrregular: false,
  },
  {
    id: 'v5',
    base: 'take',
    past: 'took',
    participle: 'taken',
    meaning: '가져가다/타다',
    example: 'It took me two hours to get there.',
    isIrregular: true,
  },
  {
    id: 'v6',
    base: 'see',
    past: 'saw',
    participle: 'seen',
    meaning: '보다',
    example: 'I saw him at the station yesterday.',
    isIrregular: true,
  },
  {
    id: 'v7',
    base: 'do',
    past: 'did',
    participle: 'done',
    meaning: '하다',
    example: 'She did her homework before dinner.',
    isIrregular: true,
  },
  {
    id: 'v8',
    base: 'buy',
    past: 'bought',
    participle: 'bought',
    meaning: '사다',
    example: 'He bought a new laptop last week.',
    isIrregular: true,
  },
  {
    id: 'v9',
    base: 'speak',
    past: 'spoke',
    participle: 'spoken',
    meaning: '말하다',
    example: 'I spoke to the manager about the issue.',
    isIrregular: true,
  },
  {
    id: 'v10',
    base: 'study',
    past: 'studied',
    participle: 'studied',
    meaning: '공부하다',
    example: 'We studied English for three hours.',
    isIrregular: false,
  },
];